# @Author: token
# @Date:   2020-08-07T08:20:24+08:00
# @Last modified by:   token
# @Last modified time: 2020-08-07T14:37:10+08:00
#全局
global:
  replicas: 1
  image:
    registry:
    tag:
    #namespace: token
    pullsecrets:

#lbl-front配置
lbl-front:
  enabled: true
  ingress:
    enabled: false
    # Used to create an Ingress record.
    hosts:
      lblfront: lbl.default.net

#xcx配置
xcx:
  enabled: true
  message:
    name: token
  ingress:
    enabled: false
    # Used to create an Ingress record.
    hosts:
      hello: xcx.default.net
