# @Author: token
# @Date:   2020-08-07T08:27:51+08:00
# @Last modified by:   token
# @Last modified time: 2020-08-07T08:42:24+08:00
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lbl-front
    release: {{ .Release.Name }}
  name: lblfront
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: lblfront
    port: {{ .Values.lblfrontPort }}
    targetPort: lblfront
  type: ClusterIP
  selector:
    app: lbl-front
    release: {{ .Release.Name }}
