# @Author: token
# @Date:   2020-08-07T08:28:13+08:00
# @Last modified by:   token
# @Last modified time: 2020-08-07T14:18:48+08:00
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xcx
    release: {{ .Release.Name }}
  name: xcx-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: xcx
    port: {{ .Values.xcxPort }}
    targetPort: xcx
    nodePort:
  type: NodePort
  selector:
    app: xcx
    release: "{{ .Release.Name }}"
