# @Author: token
# @Date:   2020-08-07T08:27:51+08:00
# @Last modified by:   token
# @Last modified time: 2020-08-07T14:18:41+08:00
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xcx
    release: {{ .Release.Name }}
  name: xcx
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: xcx
    port: {{ .Values.xcxPort }}
    targetPort: xcx
  type: ClusterIP
  selector:
    app: xcx
    release: {{ .Release.Name }}
